### ISSUE TITLE
Dashboard optimizations

### ISSUE THREAD

**Issue by btkostner** [elementary/houston#101]
Doing some programming and having 11 or so issues on a project slowed dashboard load times quite a bit. We should try looking at some options for making it faster, as it's only going to get slower the more stuff we add to it.

First thing that comes to mind would be to create a separate projects page. One extra click for the user, but considerably less logic for us, as we don't have to load everything for every project on the dashboard at once.

WIth 3 projects, and a total of 14 issues the dashboard takes 2.77 seconds to load
##

**Comment by aroman** [comment]
yeah, i think the best might be to have an explicit "import projects" button to scan the user's GitHub account for new repositories. then the dashboard would only load known good repositories.

@danrabbit @cassidyjames thoughts?

**Comment by btkostner** [comment]
Another option would be to use Github hooks. That way we don't have to grab all the information when someone views the dashboard, as all of the database info should be up to date.

**Comment by danrabbit** [comment]
Yeah I'm fine with a "rescan" button and only auto-scan on first-run/when there's none yet

**Comment by fabianthoma** [comment]
@btkostner yeah I'm all for github hooks now that you can add them from the api, only issue with that is that the user setting up the repo needs admin rights on the repo
Another thing we maybe should be looking into is actually cloning the repo and doing the checks on the server, it would save us from running into API Rate limiting for doing checks.

**Comment by btkostner** [comment]
So far what I'm thinking is:
Admin of repo initializes it on houston. This will be when houston will grab everything and add it to the database.

Github accesses houston when something gets pushed to the repo. Houston then pulls what it needs (I haven't looked into what Github sends with the hooks) and rechecks the repo and updates the issues accordingly.

If there are no problems (apphub file, icon, and desktop file, build) then an (admin or contributor) of the repo can log into houston and have the release go to the approval stage.

**Comment by aroman** [comment]
that sounds pretty good to me. I think it might be helpful if there were a manual fetch button on the dashboard somewhere, since webhooks are kind of fragile (requires both houston's backend and github's backend to be online and talking to eachother at the moment of the push)

**Comment by btkostner** [comment]
I concur

**Comment by fabianthoma** [comment]
Github does resend failed hooks, so it's probably not a real issue, but I agree on keeping a button just in case.
One thing we should definitely do is check the hashes github also sends with each webhook: https://developer.github.com/webhooks/securing/

**Comment by danrabbit** [comment]
@btkostner Can this be closed in favor of #226 ?

**Comment by btkostner** [comment]
I have a feeling that the slow down is not caused by the adding of projects. It's more likely to be the authentication or grabbing all the projects the user has access to.

**Comment by btkostner** [comment]
We are now caching the projects a user has access to in the database. Closing issue.
