### ISSUE TITLE
implement modular test system

### ISSUE THREAD

**Issue by btkostner** [elementary/houston#105]
Before we start making a bunch of tests for projects, we should setup a nice way of keeping them organized, instead of placing them all into model files. Right now I'm thinking of some sort of hook style system where you would have a file like `desktop.js` that would register different errors and warnings. Then when a repo is pulled, houston would call all these files to test the code, build app, more tests, human review, and file the issue.

Some things to consider:
Tests should be able to run in parallel for the most part
Post-build tests
tests vs houston information (`apphub` file)
keep tests modular (add more tests with no houston code touched)
optional tests? (is this a thing?)

**Comment by danrabbit** [comment]
Yeah optional tests would be a thing. At some point we're going to want to have different tests depending on features. For example if an app uses glib.notification we want to make sure it's listing that it uses notifications in the .desktop and that it's app id matches etc. But also we might want to have different tests in the future when we're building extensions as well as apps

**Comment by btkostner** [comment]
I didn't implement the optional tests yet, but basic modular tests are implemented in #110

**Comment by btkostner** [comment]
From where I am standing, this is now complete. Tests are fully async, include easy docker support, and run optionally based on a dependency system.

The only thing that will possibly change in the future are the types of tests. `release`, `daily` etc
