### ISSUE TITLE
Consider aptly instead of freight

### ISSUE THREAD

**Issue by brejoc** [elementary/houston#109]
If I remember correctly, you are planning to use freight to build the Debian repositories. Have you already seen [aptly](https://github.com/smira/aptly), which seems more active and also had a REST API which lets you...

    upload packages using HTTP, manage your repositories, snapshots, published repositories etc.

This might better suite your needs, since you need to interface the repo anyway.

**Comment by danrabbit** [comment]
Cody's been playing with Aptly today and so far it sounds like he likes it ;p I'm going to go ahead and close this issue since he's considering it heh

**Comment by brejoc** [comment]
:+1:  :)
