### ISSUE TITLE
Test uniqueness of application name

### ISSUE THREAD

**Issue by btkostner** [elementary/houston#117]
If an application tries to publish with a name that already exists, give an error
If an application tries to publish with a new name give a warning about update breaking (possibly error)

**Comment by stuartlangridge** [comment]
Do applications really need a unique name? They have a unique identifier so this isn't a technical issue, and I think it's reasonable to have more than one app named, say, "World Clock"; other app stores allow that.

**Comment by danrabbit** [comment]
I think in this case "name" means package and binary names

**Comment by btkostner** [comment]
Sorry, this was more of the way the Houston and aptly works right now. Aptly will parse the package name automatically which might cause conflicts if there are multiple packages with the same name (from what I have seen so far). Once we get this up and running with some tests (get a nice complete working developer environment) we can see if this is an actual concern.

**Comment by btkostner** [comment]
I'm closing this now that we use reverse domain name scheme for everything.

`com.github.owner.repo` like `com.github.elementary.houston`.
