### ISSUE TITLE
Use SHA256 encryption

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#155]
W: http://packages.elementaryos.org/houston/dists/xenial/InRelease: Signature by key A41CE8092290C9FBBA46AA7358A47736A8287C6E uses weak digest algorithm (SHA1)`

**Comment by btkostner** [comment]
Why not SHA512?

**Comment by lewisgoddard** [comment]
That would work equally well, but both are currently vulnerable to overflow attacks with significantly large data.  SHA384 is not. Did you mean to close this?

**Comment by btkostner** [comment]
Yes I did, I just generated a new key using SHA512. Should I replace it with SHA384?

**Comment by btkostner** [comment]
sha384 is now implemented
