### ISSUE TITLE
we need an icon

### ISSUE THREAD

**Issue by btkostner** [elementary/houston#162]
We should get an icon for houston sometime. Places it will be used:

- GitHub authentication window
- Website favicon
- Probably maybe somewhere in the website

**Comment by btkostner** [comment]
@elementary/ux

**Comment by danrabbit** [comment]
@snwh has monochrome icons somewhere that we can add a purple background on

**Comment by danrabbit** [comment]
![128](https://cloud.githubusercontent.com/assets/7277719/14340410/183c496a-fc3c-11e5-9eb2-882143b33dd2.png)
![256](https://cloud.githubusercontent.com/assets/7277719/14340411/184dbdee-fc3c-11e5-900b-8d0eb1240f1f.png)

**Comment by danrabbit** [comment]
I think this can probably be closed since we have icons now :)
