### ISSUE TITLE
Show download count on dashboard

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#163]
A first step towards some kind of analytics. We should show developers how many times the currently published version of their app has been downloaded
##

**Comment by fabianthoma** [comment]
I have a concept implementation on how to track downloads from the nginx server into houston, I'll flesh that out and propose it when I'm back from Paris.

**Comment by btkostner** [comment]
There should be a very crud setup in [here](https://github.com/elementary/houston/blob/master/src/houston/controller/hook/aptly.js)

**Comment by cassidyjames** [comment]
Super rough mvp: just stick a total download count for the app below its app ID. 
![quick mock](https://user-images.githubusercontent.com/611168/30448244-7a617900-994b-11e7-8a8f-435e1e5005aa.png)
