### ISSUE TITLE
Automatically apply AppArmor profiles

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#165]
One of the swanky features of the new Ubuntu app review process is that the system automatically applies generic apparmor profiles:

> Snaps run under strict AppArmor profiles that prevent them from doing any harm outside of their own data space. The automated reviews just check that they will be installed using one of these pre-defined trusted profiles, otherwise the submission is flagged for manual review.
> Profiles are generic. In fact, apps don't ship the profile itself, the snappy manifest names one of the pre-defined ones (provided by apparmor-easy-prof IIRC) and the install mechanism applies that to the app when it's installed.

This seems like a pretty smart idea. We should see if those profiles are open license and consider adding apparmor profiles part of the build process

**Comment by cassidyjames** [comment]
There likely needs to be a way for an app to request certain profiles, similar to defining permissions in Android <6.0 app manifests. I.e. in the `.apphub` file (or somewhere), a developer of a photo sharing app could specify the Internet, Camera, and Pictures permissions (or something).

**Comment by danrabbit** [comment]
I think the place to start here might be in defining things that apply to everyone. For example blocking off certain no-touchy parts of the filesystem or making sure that apps can't touch gps devices without going through geoclue. Then again, if those things apply to everyone, maybe we should be figuring out how to restrict these things at the OS level instead of at the apparmor profile level hmm

**Comment by danrabbit** [comment]
Gonna close this one since the plan is to move to Snap
