### ISSUE TITLE
Include git commit in version number

### ISSUE THREAD

**Issue by fabianthoma** [elementary/houston#173]
To make it easier for developers to backtrack issues we should include the checked out version from git to the version number.
We need to decide if this is a deployment thing or if houston itself should do it.

**Comment by btkostner** [comment]
I'm thinking this should be added to `~/lib/config`. It can check for a `.git` folder and if it exists, it should append the hash to the version number at `config.houston.version`.  That way it shouldn't interfere with any other code, yet be accessible to the whole application.

**Comment by btkostner** [comment]
added to config under `config.houston.commit` and implemented in github issues
