### ISSUE TITLE
/add is not showing all repos

### ISSUE THREAD

**Issue by emersion** [elementary/houston#194]
In my account + organizations, I have access to ~200 repos. The `/add` page only shows some of them.

**Comment by cassidyjames** [comment]
This is likely a permissions issue. For example, I have access to the elementary and System76 organizations, but System76 projects are not showing. I know I do not have admin access to those repos.

**Comment by cassidyjames** [comment]
A possible solution is just a copy addition at the end of the "Add" page, like:

> ## Something missing?
> If a repo is not showing, make sure you have admin access to it. If the project is owned by an organization, you may need to be an admin of the organiztion.

**Comment by emersion** [comment]
No, that's because of paging. The /add page will be deleted soon anyway.

**Comment by danrabbit** [comment]
Since the plan is to use GitHub for adding, this is a dupe of #226
