### ISSUE TITLE
Remove references to Houston

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#218]
I believe `Houston` is intended strictly as an internal codename for the AppCenter submission process. We should not be using the string in user-facing places like the title.
- [x] Page Title
- [x] Subdomain
##

**Comment by danrabbit** [comment]
I believe the only reference left in "the UI" is the subdomain which should eventually be "developer.elementary.io" once we deploy into production

**Comment by cassidyjames** [comment]
Ah, title tag

**Comment by btkostner** [comment]
We also have some references to `Houston` and `AppHub` throughout the views, and GitHub issue templates.

**Comment by danrabbit** [comment]
Gonna close this since I think apphub stuff is covered un #222
