### ISSUE TITLE
Project without an .apphub shows as "unreleased"

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#221]
If I add a repo without an .apphub file, the dashboard considers this an "unreleased" project. Instead, it should be able to tell that it doesn't have the right file.

**Comment by btkostner** [comment]
What project did you try to add? It shouldn't be checking for any files when you add a project, only when you are testing one.

**Comment by cassidyjames** [comment]
A purposefully-not-compatible project (to try and break things!). https://github.com/cassidyjames/theme-reset

**Comment by danrabbit** [comment]
I think I might be experiencing this same issue: https://github.com/danrabbit/Spice-up/releases

Says I need to make a release

**Comment by btkostner** [comment]
@danrabbit that release is not valid semver so it gets filtered out.

**Comment by danrabbit** [comment]
Okay so we need some kind of messaging to indicate that it needs all three digits

**Comment by danrabbit** [comment]
Made #249 but doesn't seem like using semver fixed it

**Comment by cassidyjames** [comment]
Gonna close this because I don't know what the exact issue was, and I can't seem to reproduce it.
