### ISSUE TITLE
Use GitHub for adding projects

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#226]
Creating a dupe-target for "add"-related issues. The plan is to use GitHub for this and get rid of the add page

**Comment by cassidyjames** [comment]
Ah, right. This will be nice. :)

**Comment by btkostner** [comment]
#209

**Comment by btkostner** [comment]
FYI, the adding part will be implemented soon, but the removing might take a bit longer as I need to setup a cascading effect for all the database documents to ensure everything is cleaned up.

**Comment by danrabbit** [comment]
I'll split that into its own report then :)

**Comment by probonopd** [comment]
:+1: for bringing all of elementary OS to GitHub
