### ISSUE TITLE
What does "Running" mean?

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#244]
This status is not really clear. Running what? The build? Tests?

**Comment by btkostner** [comment]
The running stage means that the project is currently in flightcheck, so testing, building, and being uploaded.

**Comment by danrabbit** [comment]
We seem to have individual status' for each of those actions. Are those not implemented?

**Comment by btkostner** [comment]
We used to have them separated, but it's far more efficient to have them all run together. I would guess I missed a file when I switched it then.

**Comment by danrabbit** [comment]
Yeah there's several busy states. I guess we need to figure out which ones are unused and then removing those and then update the copy of this status to reflect what is actually happening

**Comment by btkostner** [comment]
Here is the list of steps the code currently follows.

- NEW
- INIT
- STANDBY
- QUEUE
- RUN
- REVIEW
- FINISH
- FAIL
- ERROR

Once the new GitHub API is int we won't have the `NEW` or `INIT` stages.

**Comment by danrabbit** [comment]
Okay so it sounds like these are unused:
- [] `build.jade`
- [] `hold.jade`
- [] `post.jade`
