### ISSUE TITLE
No Reports Filed

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#245]
Houston claims that it filed some reports
![](https://imgflip.com/s/meme/Maury-Lie-Detector.jpg)
[This link](https://github.com/elementary/debian-test-package/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen) determined that was a lie

**Comment by btkostner** [comment]
Most likely because of the `elementarybot` authentication credentials expiring. This will be fixed with the new GitHub API
