### ISSUE TITLE
Change .jade file names

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#246]
The current names are not very good and it's hard to find the file that contains the thing you're looking for:

- `standby.jade` sounds like a busy/queued state but is actually the submit for review action
- `build.jade` sounds like an action to initiate the build, but it's actually a busy state of being built
- `init.jade` sounds like adding a repo to Houston, but it's actually the call to create a new release tag
- `new.jade` sounds like what it does, but it links to `/init` so maybe this should be called `init` for consistency. I realize this is going away though so meh.
- `post.jade` doesn't really sound like anything, but it's the testing state
- `hold.jade` and `queue.jade` sound the same, but one is waiting to build and one is waiting to test
- `review.jade` sounds like an action, but it's a busy state for human testing
- `run.jade` sounds like an action, but it's a busy state that.. does.. something...

Having some hyphenated naming would probably help sort these files and make it more clear what's what before opening them. Some suggestions:

- `release.jade`
- `submit.jade`
- `building-wait.jade`
- `building.jade`
- `testing.jade`
- `testing-wait.jade`
- `testing-review.jade`

**Comment by btkostner** [comment]
FYI the names of those files are the same names as the steps we use in the database and throughout the code.

**Comment by danrabbit** [comment]
Ah then I guess the scope would be larger :p These names are really unclear

**Comment by btkostner** [comment]
Here is a little info on each step:

- `NEW` - A new project, yet to be setup with hooks are releases pulled
- `INIT` - Project is setup but no releases  
- `STANDBY` - Awaiting person to click the bug green button
- `QUEUE` - In line to be ran in flightcheck
- `RUN` - Currently being ran in flightcheck
- `REVIEW` - The cycle passed, and the file is in the review repo await human approval
- `FINISH` - The review finished and everything is good
- `FAIL` - The cycle finished with issues that should be posted to GitHub
- `ERROR` - Internal error during the test
- `DEFER` - Used to signal that the project or release status is dependent on the release or cycle

```
      INIT
    /   |
NEW - STANDBY - QUEUE - RUN - REVIEW - FINISH
```

```
 Projects                   Releases                  Cycle
(NEW INIT ERROR) - DEFER - (STANDBY ERROR) - DEFER - (QUEUE RUN REVIEW FINISH FAIL ERROR)
```

**Comment by danrabbit** [comment]
Gonna close this report since many of these files don't exist anymore
