### ISSUE TITLE
Use GitHub for removing projects

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#250]
After #226 is finished

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38390048-use-github-for-removing-projects?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github).

**Comment by btkostner** [comment]
This was implimented in #355
