### ISSUE TITLE
Possible to write plugins for AppCenter?

### ISSUE THREAD

**Issue by probonopd** [elementary/houston#257]
Is it possible to write plugins for AppCenter, similar to GNOME Software plugins?

I would be interested in integrating [AppImage](http://appimage.org/) better with elementary OS. Some initial work is [already underway](https://www.youtube.com/watch?v=FqVAtHdK1N0).

**Comment by btkostner** [comment]
As of right now AppCenter does not have plugin support. We are currently focused on getting integration with houston working.

Your best bet would be to make a new app specifically for AppImage management.

**Comment by probonopd** [comment]
Let me phrase this differently then, is it possible to write plugins for houston, for additional sources of metadata?

**Comment by btkostner** [comment]
As of right now there is no plugin support, but there are enough generalizations that it shouldn't be too hard to add other services. I would wait until houston is out of beta first though to ensure no big internal changes happen.
