### ISSUE TITLE
Add link to release tag in issues

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#276]
We should link to the affected release, i.e.:

> **Affects**: [v2.2.3](https://github.com/elementary/vocal/releases/tag/v2.2.3) release

**Comment by btkostner** [comment]
https://github.com/elementary/houston/blob/master/src/flightcheck/pipes/pipe.js#L166

**Comment by danrabbit** [comment]
I don't think [these owner and repo vars](https://github.com/elementary/houston/blob/master/src/flightcheck/pipeline.js#L85) are public are they? So I'm not sure we can construct a URL from the info currently probably by pipeline
