### ISSUE TITLE
Create appdata file if it does not exist

### ISSUE THREAD

**Issue by btkostner** [elementary/houston#277]
@Philip-Scott brought up a good point, saying we have most of the information needed already.

> the app ID (which has to use RDNN anyways), name and license are already on the project. Summary could be Repo's description and you already have the releases info don't you?

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38524297-create-appdata-file-if-it-does-not-exist?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github).

**Comment by danrabbit** [comment]
Could we theoretically submit a PR with a partially filled out appdata file? I think ideally we want the appdata.xml in the repo so we're good open source citizens and that

**Comment by cassidyjames** [comment]
@danrabbit holy shit that'd be magical. I really like that.

**Comment by cassidyjames** [comment]
Looking at this three years later, I think we have been leaning into using AppData as the source of truth. I could see this making sense as a sort of hand-holding first step for a new app, but I'm not sure if it's worth the time to do.

**Comment by danrabbit** [comment]
Yeah, gonna close this since it's no longer applicable in a flatpak world
