### ISSUE TITLE
"Package is not valid reverse domain name scheme" not specific enough

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/houston#302]
See: https://github.com/Philip-Scott/Spice-up/issues/44

It complained about the package name even though Source was the wrong one 

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39267792-package-is-not-valid-reverse-domain-name-scheme-not-specific-enough?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github).

**Comment by btkostner** [comment]
Closing because the error message is now this
> `Source is not correct. It should be "${this.pipeline.build.name}"`
