### ISSUE TITLE
Build stripe ID into the AppData file

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#321]
As far as I understand, this is the next step for stripe integration. We're going to be using the key `<x-appcenter-stripe>`

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/39783925-build-stripe-id-into-the-appdata-file?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github).

**Comment by btkostner** [comment]
Added in #322
