### ISSUE TITLE
Apply the DEP-11 specification correctly

### ISSUE THREAD

**Issue by tintou** [elementary/houston#335]
The …/apphub/dists/xenial/main/appstream/ folder should be named …/apphub/dists/xenial/main/dep11/ (just like it's done in debian http://fr.archive.ubuntu.com/ubuntu/dists/xenial/main/dep11/ )

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40521822-apply-the-dep-11-specification-correctly?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F27692469&utm_medium=issues&utm_source=github).

**Comment by tintou** [comment]
I think that this bug will be covered by https://github.com/btkostner/aptly/pull/2

**Comment by btkostner** [comment]
This should be fixed already but I have yet to test in production.
