### ISSUE TITLE
Appstream metadata not properly generated after publishing an app

### ISSUE THREAD

**Issue by nathandyer** [elementary/houston#393]
I just published com.github.needle-and-thread.vocal. When I refreshed software sources and opened AppCenter I thought the Vocal I was purchasing was my app, but it still had the outdated appstream metadata, so I actually bought com.github.btkostner.vocal. 

Houston should regenerate the appstream metadata correctly after an app gets published.

**Comment by btkostner** [comment]
Due to securty reasons, the signing key we use for the repository is not held on the repository server. So we would need to keep a script running on another server that re-publishes the repository every X minutes.

**Comment by danrabbit** [comment]
What about just moving things around a bit so like if the package build passes then we generate the appstream data and then wait for that to complete and then we publish the repo?

**Comment by btkostner** [comment]
Because appstream generator works on the repository, not the package. The package needs to be in the repository to generate, then we need to update the repository with the latest generated version of appstream data.

**Comment by danrabbit** [comment]
Ah that's kind of dumb. So then we need to update the repo twice every time we publish a package.

**Comment by btkostner** [comment]
With a 15 minute delay to ensure appstream is generated. I'll probably just make a small process that republishes the repo every 15 minutes. Seems simpler than adding a queue.

**Comment by btkostner** [comment]
Small process is done and working. Delay is not optimal, but we can revisit some time later.
