### ISSUE TITLE
Houston is adding an extra <custom/> tag to appdata

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#396]
as seen in the vocal appdata.xml:

```
  <custom>
    <value key="x-appcenter-color-primary">#603461</value>
    <value key="x-appcenter-color-primary-text">#fff</value>
    <value key="x-appcenter-stripe">pk_live_a26MMjS4MyiJyBOXCbsPkKlz</value>
  </custom>
  <custom/>
```

You can see [in their repo](https://github.com/needle-and-thread/vocal/blob/master/data/com.github.needle-and-thread.vocal.appdata.xml) there's just the one tag so it must be our fault

**Comment by btkostner** [comment]
Closing because we now use `xmlstarlet` instead of weird javascript xml parsers for adding the stripe key.
