### ISSUE TITLE
Dashboard not showing some repositories

### ISSUE THREAD

**Issue by carlosgj94** [elementary/houston#404]
My Dashboard doesn't show one the repositories I have. The thing, is that the Dashboard shows everything but that one. 
It's a new repo, I don't if that can make something work bad...
I have double checked the Dashboard and the integration. In fact, **if I click to give access to all the repositories, I can see all of them but the new ones (from today).**

In case you need the link: https://github.com/carlosgj94/hider-gtk.

**Comment by danrabbit** [comment]
Should be addressed by #401

**Comment by btkostner** [comment]
It's due to the cache, which currently is set pretty high (24 hours). I have a PR open for lowering it down to just 1 hour. I would recommend just waiting the 24 hours and checking after that. If it's still a problem let me know and I'll dig into the database to see what's up.

**Comment by carlosgj94** [comment]
Sure, I will check tomorrow.
