### ISSUE TITLE
Houston is building with an outdated Granite library

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/houston#415]
It appears that houston might be building apps using an older version of granite. AppCenter apps have their about menu broken, as well as some other small issues not prevented when building manually

![screenshot from 2017-04-22 17 55 40](https://cloud.githubusercontent.com/assets/10786508/25309474/1a816c3c-2783-11e7-95bb-6abcdbda7f5b.png)

**Comment by btkostner** [comment]
It shouldn't be _too_ out of date. It's using liftoff to build the deb packages, which _should_ grab the latest released version of the library during build.

**Comment by Philip-Scott** [comment]
Could it be building the apps for a whole different ubuntu version then? (Maybe it's building trusty packages instead of xenial)

**Comment by danrabbit** [comment]
I think Cody is going to release a new Granite soon and hopefully that will fix it

**Comment by btkostner** [comment]
`amd64` on `xenial` https://github.com/elementary/houston/blob/master/src/flightcheck/pipes/Liftoff/index.js#L66

**Comment by cassidyjames** [comment]
Tossing this issue in there since it's linked https://github.com/elementary/stylesheet/issues/92

**Comment by Philip-Scott** [comment]
@btkostner Don't we have a different version of granite and GTK than on the default ubuntu? We might not be pulling the elementary ppa

**Comment by btkostner** [comment]
I'll take a look at the liftoff code, althought that might be better suited to @codygarver.
