### ISSUE TITLE
Web tool to preview theme colors/banners

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#428]
A couple of devs have asked me if there's a way to preview the primary and primary-text colors and how they'll be used. It could be interesting to build a super simple web tool that let you drop in the color variables and it applied the CSS to a mock banner.

Not sure if this technically belongs in houston, but I figured I'd file it away somewhere. :)

**Comment by danrabbit** [comment]
I'm not sure this really makes sense as a web tool. Seems like it would make more sense as a command line flag in AppCenter to load an appdata.xml file or somerthing

**Comment by cassidyjames** [comment]
Yeah after thinking about this, it could belong in AppCenter or even just have the widget in Granite with some entries for colors.
