### ISSUE TITLE
Repositories not showing up in developer Dashboard

### ISSUE THREAD

**Issue by thejambi** [elementary/houston#453]
After setting up the AppCenter integration, recently created repositories are not showing up in Dashboard. Does it take a certain amount of time for repositories to show up?

**Comment by btkostner** [comment]
There is a 1 hour cache for projects. If it does not show after that I would recommend logging out, revoking access [here](https://github.com/settings/connections/applications/98b884c6dad0f50a4012) and trying to log in again. Feel free to join the [gitter channel](https://gitter.im/elementary/houston) if they still do not show.

**Comment by thejambi** [comment]
Hm. Not showing up now, but I'll try that again if they're not showing up tomorrow, too. Will get on gitter if needed. Thanks!

**Comment by thejambi** [comment]
It's all set now. Resetting things and setting it up again seems to have fixed it. Things are showing up as I'd expect. Cool!
