### ISSUE TITLE
Insists on com.github. app name

### ISSUE THREAD

**Issue by phw** [elementary/houston#466]
My app already has a proper name of `com.uploadedlobster.peek`, yet the app store validation insists on me shipping a `com.github.phw.peek.desktop`

I am not really interested in changing the name of an app already in use by many people without good reason. I also don't see how I could change it just for the Elementary App store, and I am not really interested in maintaining a workaround just for this.

Any ideas? I think it should be possible to override the fully qualified app name.

**Comment by danrabbit** [comment]
Closing as a duplicate of #436
