### ISSUE TITLE
Test that uninstalling leaves filesystem as it was

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#472]
A useful test could be that installing and then uninstalling an app properly cleans up its files instead of leaving junk behind.

**Comment by cassidyjames** [comment]
We would also need to define (and document for developers) what files need to be removed and what sorts of files (and locations) it's okay for them to remain. I.e. a project folder under ~/ might make sense to keep around, but I imagine anything outside of the home directory (or dotfiles?) should be removed.

**Comment by danrabbit** [comment]
Closing since we're moving to flatpak and this is no longer relevant when apps are sandboxed
