### ISSUE TITLE
Stray help icon on the Developer homepage

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#478]
![screenshot from 2017-06-29 16 15 29](https://user-images.githubusercontent.com/7277719/27714523-3d6d1ae6-5ce6-11e7-8ccb-f34d8ecfa0e5.png)

**Comment by btkostner** [comment]
Is this the help icon for the FAB? I'm going to guess it's a cache issue if it is.

**Comment by danrabbit** [comment]
Yeah it's showing on https://developer.elementary.io/ when it should only show in the dashboard.
