### ISSUE TITLE
Color Picker's Stripe key not being added to AppStream metadata

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#484]
Looks like the cause behind https://github.com/elementary/appcenter/issues/377

**Comment by cassidyjames** [comment]
com.github.ronnydo.colorpicker

**Comment by cassidyjames** [comment]
https://appstream.elementary.io/appcenter/html/xenial/main/metainfo/com.github.ronnydo.colorpicker.html

**Comment by btkostner** [comment]
It's because of the appstream not passing validation. If it doesn't pass validation then it don't try to change it / add the stripe key in.

**Comment by danrabbit** [comment]
If it doesn’t pass validation then it shouldn’t be publishable. What happened to the test there? :p

**Comment by btkostner** [comment]
I thought we didn't want to stop based on appstream validation. I'll change it to fail the build then.

**Comment by lewisgoddard** [comment]
How many fail validation? We don't want to stop every build we have.

**Comment by btkostner** [comment]
@lewisgoddard That is a good question, sadly I do not have analytics for the answer, but I would guess not many.

**Comment by danrabbit** [comment]
Well we probably don’t need to fail the `pedantic` settings with things like not having a period at the end of the summary, but if the app data file is just invalid then it wouldn’t show in AppCenter at all right?

**Comment by btkostner** [comment]
[This issue](https://github.com/RonnyDo/ColorPicker/issues/17) has 1 warning and 1 info. I assume both are just style changes and would still show in AppCenter.
