### ISSUE TITLE
elementary os 0.4.1

### ISSUE THREAD

**Issue by gfubing** [elementary/houston#486]
elementary os 0.4.1系统用终端安装系统更新好慢，安装一个输入法慢又多少软件可以安装无法运行打开最主要多优化系统地安装和运行系。

**Comment by danrabbit** [comment]
This issue tracker is for AppCenter Dashboard. Support questions about elementary OS should be directed to elementaryos.stackexchange.com

**Comment by gfubing** [comment]
要设置一个elementary os系统论坛让全世界的人相互沟通相互学习。
