### ISSUE TITLE
Repository missing from dashboard

### ISSUE THREAD

**Issue by jendrikseipp** [elementary/houston#497]
I have created a new repo https://github.com/jendrikseipp/rednotebook-elementary for testing the release process. However, it doesn't show up in the dashboard (https://developer.elementary.io/dashboard). All my other repos appear just fine. Any idea what could be the problem?

**Comment by btkostner** [comment]
Try to log out and back on and see if that resolves everything.

**Comment by jendrikseipp** [comment]
Thanks, this did fix the issue!

**Comment by matzipan** [comment]
Hi - I have a similar issue but logging out and back in didn't fix it. Should I open a new issue ?

**Comment by btkostner** [comment]
@matzipan you can just talk on here. Is the repo in question part of an organization?
