### ISSUE TITLE
Show Error when missing .desktop or icon files

### ISSUE THREAD

**Issue by fabianthoma** [elementary/houston#53]
Show an error & helpful steps to fix it when we are missing an icon and/or .desktop file.

**Comment by danrabbit** [comment]
Would this be too early to file an issue and just use the generic "Fail. Check your GitHub Issues" messaging?

**Comment by aroman** [comment]
no, i don't think we will have/should have a 'generic fail'. code-wise, there's no problem with filing regular issues if they pertain to .desktop files or icon files.

**Comment by danrabbit** [comment]
Sorry I meant do both of those things ;D Both file and issue and use our existing fail status which tells the user to check their GitHub issues

**Comment by btkostner** [comment]
Added tests for this in #110
