### ISSUE TITLE
Allow custom links in appdata.xml

### ISSUE THREAD

**Issue by geigi** [elementary/houston#554]
Hey,

I'm trying to include a patreon link in my appdata.xml where people that cannot use Stripe still can support my project. Is there currently any place where I can put a link like this? I previously added it to the summary but this is not allowed anymore: 
```
com.github.geigi.cozy.appdata.xml:com.github.geigi.cozy.desktop:32
    The description contains an URL. This is not allowed, please use the <url/> tag 
    to share links.
```

**Comment by btkostner** [comment]
Look under the `url` tags. There is one for donations. 

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by geigi** [comment]
Ahh thats cool, Cheers :)
