### ISSUE TITLE
Allow hyphen/minus in domain names (and GitHub usernames) to be mapped to underscore

### ISSUE THREAD

**Issue by smcv** [elementary/houston#566]
Separated out from https://github.com/elementary/houston/issues/436 as requested.

DNS domain names (and GitHub usernames, which are syntactically the same) can contain hyphen/minus. D-Bus well-known names are allowed to either hyphen/minus or underscore, but using hyphen/minus interacts poorly with various D-Bus-adjacent specifications and APIs that use reversed domain names, do not always allow hyphen/minus, but usually do allow underscore.

The meme I'm trying to spread as a D-Bus maintainer is that app IDs, D-Bus names and object paths, etc. should be derived from DNS names like this:

* replace `-` with `_`
* if a component starts with a digit, prepend `_` to it
* example: 7-zip.org (which happens to hit both the problem cases) might publish `org._7_zip.Archiver`

This cannot result in a collision with other valid DNS domain names, because DNS domain name components aren't allowed to contain `_` or start with `-`, so there is no ambiguity.

When verifying that an app's app ID corresponds to a GitHub username and repository, please allow apps where the app's maintainer has carried out this transformation: for example, https://github.com/parnold-x/nasc should be allowed to use `com.github.parnold_x.nasc` as its app ID in Elementary (see also <https://github.com/parnold-x/nasc/issues/67>), and if `https://github.com/3d/App` existed, it should be allowed to use `com.github._3d.App`.

Patches for Desktop Entry Specification recommending this, which should hopefully be applied soon: https://bugs.freedesktop.org/show_bug.cgi?id=103216

Patch for D-Bus Specification, likewise: https://bugs.freedesktop.org/show_bug.cgi?id=103914

**Comment by smcv** [comment]
> for example, https://github.com/parnold-x/nasc should be allowed to use `com.github.parnold_x.nasc` as its app ID in Elementary

It would be fine if Elementary *also* allowed it to use the soon-to-be-deprecated form `com.github.parnold-x.nasc` for backwards compatibility, of course.

**Comment by btkostner** [comment]
So, we started doing a better job with this on houston v2 (now released for CI and building), but it seems we are having issues with different parts. For reference, here is a list with restrictions:

- dbus: Underscores like this issue
- debian packaging: No underscores (dashes)
- binary files: Underscores are weird (dashes)

I think the best way going forward is to put `rdnn` as a function that can return the underscore _or_ the dash version. Also, due to the weird nature of starting parts with numbers, I think we should just _highly_ recommend against starting any section with numbers.

```js
rdnn('com.github.something.0-that_should-be-fixed', 'dashed') => 'com.github.something.-0-that-should-be-fixed'
rdnn('com.github.something.0-that_should-be-fixed', 'underscore') => 'com.github.something._0_that_should_be_fixed'
```

**Comment by btkostner** [comment]
This should be considered fix going forward now: https://github.com/elementary/houston/releases/tag/v2.0.0
