### ISSUE TITLE
Houston insisted I use an old name for my app's Reverse Domain Name

### ISSUE THREAD

**Issue by alcinnz** [elementary/houston#569]
I have a [repository](https://github.com/alcinnz/Odysseus/) which I have previously renamed away from an old misspelling. However when I went to submit that app to the AppCenter through Houston it insisted I use the old mispelled name in my reverse domain name, a name I found unacceptable.

I found a work around where I created a seperate "release" repository which had an acceptable name from the start, so I am happy now. But it would have been nice if Houston saw the current name before the first submission to the site, rather than some older name.

**Comment by btkostner** [comment]
Just as a note, we have not worked on name changes in our repository yet, so it's quite possible that things will break.

You will need to remove the integration from the repository, then re-add it. This should remove it from our database and re-add it with the new GitHub information. If you can, please let me know the name of the repository so I can ensure it gets removed correctly.

**Comment by alcinnz** [comment]
Thanks for your help, I've just uninstalled AppCenter from my GitHub installation. 

My repository was alcinnz/Odysseus (coming up as "oddysseus" in Houston), but I've been releasing through alcinnz/Odysseus-web.

Please tell me once you've purged my repositories and it'll be a good time to reinstall your extension.

**Comment by btkostner** [comment]
You should be able to add it again now. After adding it, make sure to log out and back on to the dashboard so it updates the repo list.

**Comment by alcinnz** [comment]
Thanks! That worked! 

I'll correct my in-code RDNN again and publish it. 

---

P.S. The last time I published I say my AppStream metadata wasn't being used by AppCenter. Will ensuring it uses the given RDNN and is installed to /usr/share/metainfo correct that problem?

Also I don't know whether to close this issue. It's solved for me, but I don't know whether you want to fix it for all/most future developers experiencing it.

**Comment by btkostner** [comment]
As long as you have an appstream metadata file with the same RDNN that gets installed to `/usr/share/metainfo` it should work. There are also tests that will ensure it gets installed correctly and is readable. Sounds like the problems you where having were because of the RDNN being different than the repository. Should be all good now with the repository changed.

I'm going to close this issue. Feel free to re-open or comment on it if you have more questions. It will be here if anyone searches for this issue.

In the mean time, I agree that this needs some work and fixes. A lot fo that is going to be extending the GitHub web hooks to ensure everything is kept in sync with GitHub's database. The second part is going to be creating transition packages to ensure upgrades don't break user's systemes. Both of which are on my list, but pretty far down.

**Comment by alcinnz** [comment]
Thanks for all your help, and have a happy new year's. 

I've just re-released my app to Houston.

**Comment by alcinnz** [comment]
I just checked the appcenter and apt, and it appears that appcenter still isn't seeing my appstream metadata. 

To be specific the symptoms are that it doesn't show all the links I've specified in my footer, it has the description my debian packaging rather than AppStream, it has no screenshots, and doesn't show in the carousal for new apps. 

Can I please get some help debugging this?

**Comment by btkostner** [comment]
It seems that the appstream data is built for the repository.
https://appstream.elementary.io/appcenter/html/xenial/main/metainfo/index.html

It might be cached on your system then. Try running these commands and checking the output.
```sh
sudo apt update
sudo appstreamcli search odysseus 
```

That should show two different ones, one of them being `com.github.alcinnz.odysseus.desktop`. If that doesn't show try running `sudo appstreamcli refresh-cache --force` and trying again.

**Comment by alcinnz** [comment]
Hmm interesting, this test passes for me but the AppCenter entry still doesn't contain all my metadata.

I'm about to check on a clean VM, but it may be helpful if you can confirm whether you are having the same issue I'm having. So do you see any screenshots for Odysseus when viewing it through AppCenter?

**Comment by alcinnz** [comment]
O.K., it works perfectly on a clean VM. So nevermind about that test.

However when I go to the Internet section on AppCenter I find two entries for Odysseus. I think this might be confusing to someone who might be about to install Odysseus. So can you please remove or deprecate the com.github.alcinnz.odysseus-web one?
