### ISSUE TITLE
Remove com.github.alcinnz.odysseus-web from appdata

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#576]
We're getting an error here: https://appstream.elementary.io/appcenter/html/xenial/main/issues/com.github.alcinnz.odysseus-web.html

It's because he renamed to odysseus (no `-web`) so I guess we need to remove this appdata

**Comment by btkostner** [comment]
We also need to create a transition package, remove all the other old packages, and then do this.

**Comment by btkostner** [comment]
I'm going to close this. Transition package is made, and appstream _should_ be updated on the server. It may take time to propagate though. Let me know if you are still experiencing this after a `sudo apt update && sudo appstreamcli refresh-cache --force` in a day or so.
