### ISSUE TITLE
Persistent, Centralised user accounts for tracking purchases

### ISSUE THREAD

**Issue by Lewiscowles1986** [elementary/houston#588]
Following on from https://medium.com/@cassidyjames/we-dont-have-any-sort-of-centralized-account-service-at-this-point-but-we-do-realize-that-s-a-5e6827b7875

It looks like there is a database email is a field that is available https://github.com/elementary/houston/blob/master/src/lib/database/user.js 
 (since users don't login I'm assuming that's for devs?). I'll need to do more digging but essentially.

* Need a way for a user to have multiple elementary machines, sharing an account to bypass nag screens after signing in with an email.
    * In-case they need to destroy a machine, or purchase a new one and cannot (for whatever reason) simply move over current elementary install.
    * In-case a user has more than one machine

I've noticed there is no password field, but would I be correct in assuming that because it's mongo a simple check for the existence of a password field would be a good direction to handle adding one?

This does raise questions about user-personas. My naive thinking is centred around lack of friction for what very well might be an edge-case.

It could potentially allow less-desirable behaviour if the app store were to mature and elementary become popular, then it would follow someone could buy a license and either as a contractor give clients their user-credentials, or use for multiple machines that separate people do.

It's kind of moot at the point they could opt not to pay and seems a lot of effort to go to for apps @ <$100

**Comment by lewisgoddard** [comment]
This is heavily related to elementary/appcenter#156

**Comment by Lewiscowles1986** [comment]
Closing as it'll require less effort to follow #156 than modify this (then have to worry about amount of info stored etc)

**Comment by btkostner** [comment]
Just as a note, we have been looking into this, but we are not planning on having it be part of Houston. It will most likely be be a part of our accounts system instead: https://github.com/elementary/accounts
