### ISSUE TITLE
Error Encountered Processing com.github.jmoerman.go-for-it.

### ISSUE THREAD

**Issue by JMoerman** [elementary/houston#602]
I don't know if this is the correct place to report this, I wouldn't know where else to report this.

I while back I attempted to push a new (small) update for _Go For It!_ to AppCenter, but it got stuck.
I haven't had time to look into this, until now.

The popup message just states the following:
```
Error Encountered Processing com.github.jmoerman.go-for-it.
This is most likely a problem with this website.
```

I don't have any more information about this, unfortunately.

Can someone find out what has gone awry and solve the issue / give instructions on how to solve the issue?

**Comment by btkostner** [comment]
The reason this is failling is because of https://github.com/elementary/houston/issues/511. The quick solution _should_ be to create a new release.

**Comment by JMoerman** [comment]
Thank you for the information! I will let you know the results when pushing out a new release.
