### ISSUE TITLE
Match branches to dists for publishing

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#604]
I think the expected workflow for developers who want to support both Loki and Juno is to have a `master` or `juno` branch with an accompanying `deb-packaging-juno` branch for publishing to Juno and a `loki` branch with an accompanying `deb-packaging-loki` branch for publishing to Loki

**Comment by btkostner** [comment]
Fixed in c6dc5f6dc6c54fa3ad7339adbf7c98b01a30f423
