### ISSUE TITLE
Donate via terminal

### ISSUE THREAD

**Issue by ghost** [elementary/houston#616]
A while ago I suggested to snapcraft to make it possible to donate to developers using the terminal:

https://forum.snapcraft.io/t/tipping-developers-using-the-terminal/4064

I think that this idea could be used for elementary OS too, but for regular apps. Some people love the terminal, it could be used to help fund projects, it's another way to incentive developers.

**Comment by danrabbit** [comment]
I'm going to close this since it will be automatically resolved by shipping https://github.com/elementary/flatpak-authenticator
