### ISSUE TITLE
com.github.ztefn.haguichi is Being Tested by a Human

### ISSUE THREAD

**Issue by ztefn** [elementary/houston#620]
_Sit back and have a drink. We'll let you know if anything is amiss._

I have submitted the new 1.140.0 release last Saturday, so I've had more then a few drinks by now...

Don't want to sound impatient, but the message implies a swift process. If it takes days or even weeks please say, so that I can adjust my expectations accordingly! Right now I'm left in the dark...

**Comment by danrabbit** [comment]
We appreciate your patience! Things are quite busy right now with trying to get Juno Beta out the door so our resources are a little impacted. This is also quite a large update with lots of changes which makes it more difficult to review. Hang tight, we'll get there as soon as we can

**Comment by ztefn** [comment]
No problem, that's totally cool! Can't wait to test out my app on Juno. A after all the newly added shortcuts window will only work there... =)

I also look forward the hear about packaging changes needed for Juno (if any).
