### ISSUE TITLE
FontAwesome 5 Pro icons broken

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#623]
Looks like we're not loading the CSS. Previously reported at https://github.com/elementary/website/issues/1967

**Comment by lewisgoddard** [comment]
If we upgrade Font-Awesome to fix that, we will also need to upgrade every other icon on the site.

**Comment by cassidyjames** [comment]
@lewisgoddard we did so on the main site, so I think we're just out of sync here.

**Comment by lewisgoddard** [comment]
Is that all of them? Can this be closed?

**Comment by btkostner** [comment]
I think so, but it has yet to be deployed

**Comment by btkostner** [comment]
Deployed. Feel free to open again if there is an icon missing.

**Comment by cassidyjames** [comment]
I think this broke a lot of other styles… perhaps a conflict between the fontawesome `fab` and the floating action button `fab`?

![screenshot from 2018-06-15 09 57 43](https://user-images.githubusercontent.com/611168/41477843-cf47b178-7082-11e8-8797-57c1e7b6b098.png)

**Comment by cassidyjames** [comment]
The GitHub button is also broken
![image](https://user-images.githubusercontent.com/611168/41477886-f7d190dc-7082-11e8-8722-6a7c0cfc1420.png)

**Comment by btkostner** [comment]
Damn you cloudflare :fist_raised: 

Fixed GitHub icon. Redeploying. Should be up in a couple of minutes

**Comment by cassidyjames** [comment]
Hey that's better. Thanks @btkostner!
