### ISSUE TITLE
Consider using a pull request system for reviewing apps

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#625]
Random idea here, I think that there's some features I would really like to be able to use during app reviews that could be solved by having app reviews done via pull request somehow. Example:

A developer submits a new app to be reviewed in AppCenter. Houston opens a new pull request that does something like add their RDNN to a file or something. Doesn't really matter what the actual contents of the pull are. As a result of this:
* We automatically see the requested review in Slack as soon as it is submitted
* We can see how long an app has been waiting to be reviewed
* We can assign people to review apps
* We can track review discussion in a public place
* We can maintain a PR template with a checklist for human reviewers
* Bonus: we have one less piece of UI to maintain

**Comment by btkostner** [comment]
On the flip side of this, supporting Gitlab would be harder. Esspecially because it would require the reviewer to have access (an account) to the Gitlab instance, which may be much harder if it's a private instance.

**Comment by danrabbit** [comment]
@btkostner I think the idea would be that it would operate on a repository that is controlled by elementary, not on the app's repository

**Comment by danirabbit** [comment]
This is now done yay
