### ISSUE TITLE
Add vala-lint option to CI

### ISSUE THREAD

**Issue by mdh34** [elementary/houston#627]
It would be really great if Houston CI would have an option to enable vala-lint during testing for vala projects to enforce code style

**Comment by btkostner** [comment]
Houston makes no judgement on the language it's building, or how you set it up (aside from the necessary package building). Linting can change between projects, languages, organizations, etc. As such, if you want to use `vala-lint` I would recommend making it part of your CI process (seperate from building) on `travis` or what ever other CI you are using.
