### ISSUE TITLE
Test for ID includes outdated expectations

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#634]
https://github.com/danrabbit/lookbook/issues/35

`.desktop` is no longer expected to be at the end of appstream IDs.

**Comment by danrabbit** [comment]
@btkostner No changes to file name, just the `<id/>` tag in *.appdata.xml

**Comment by btkostner** [comment]
Fixed in: https://github.com/elementary/houston/releases/tag/v2.0.0

**Comment by babluboy** [comment]
@btkostner I had the same issue while building Nutty for Juno:
https://github.com/babluboy/nutty/issues/25

My id in the[ appdata file](https://github.com/babluboy/nutty/blob/edc713cc104e49ab0212f0514ab88cceac3aac71/data/com.github.babluboy.nutty.appdata.xml#L4) is defined as:
<id>com.github.babluboy.nutty.desktop</id>

Do I need to change the id value ?

**Comment by btkostner** [comment]
Yes. The appstream id will need to be changed. Houston ci should warn you.
