### ISSUE TITLE
Builds are failing that shouldn't be running

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#636]
AppCenter (and others) are [currently failing to build on Loki](https://travis-ci.org/elementary/appcenter/builds/402006435?utm_source=github_status), but they shouldn't be building for Loki. Not sure if this is user error or a problem with Houston

**Comment by btkostner** [comment]
There is a loki branch for AppCenter: https://github.com/elementary/appcenter/tree/loki
And a loki packaging branch: https://github.com/elementary/appcenter/tree/deb-packaging-loki

**Comment by danrabbit** [comment]
Well shit
