### ISSUE TITLE
content_rating can't be omitted

### ISSUE THREAD

**Issue by peteruithoven** [elementary/houston#641]
Currently the `content_rating` tag can't be omitted, while this should be allowed. 
This should be fixable by updating Appstream. 

@cassidyjames in Slack:
> this is actually a bug in the validator. They recently updated the spec to allow omitting results when the value is "none," but the validator doesn't understand when they're all omitted.
> Let me find the link :slightly_smiling_face:
> https://github.com/ximion/appstream/issues/198#issuecomment-415033247
> It looks like a fix has been committed to Appstream, but we'll need that to get updated in Houston.
> What you can do for now is add something like a `<content_attribute id="social-info">none</content_attribute>` child tag instead of it being empty.

This should prevent people getting the "Missing AppStream OARS tags" issue after publising. Example:
https://github.com/peteruithoven/resizer/issues/29
It might also be related to the "Missing AppStream OARS attributes" error. Example: 
https://github.com/peteruithoven/resizer/issues/30

I guess one downside of this is that apps that should include a content rating tag can't be warned.

**Comment by btkostner** [comment]
Removed our houston test for that, so this so no longer be an issue.
