### ISSUE TITLE
Wiki: Packaging branches

### ISSUE THREAD

**Issue by peteruithoven** [elementary/houston#642]
The wiki is missing documentation on distribution/ packaging branches. Since I can't edit it, or start a pull request I'm opening this issue with the following proposal.
(I've used the term "packaging" branches, even though the blog called it "distribution" branches because that's what the word used in the actual branches.) 

> ## Packaging Branches 
> The AppCenter publishing process and Houston CI use git branches to determine which distributions to build for. When no packaging branch is added, a package is only build for the latest elementary OS version, currently Juno. It's also possible to put all the changes required to build for that latest version in a generic `deb-packaging`. This could enable non elementary OS specific repo's to publish to the AppCenter. 
> To target specific elementary OS versions branches named: `deb-packaging-[version]` can be used. To target Loki you'll need to add a branch named `deb-packaging-loki`.
> These branches are checked when when a new version is submitted to the AppCenter or when Houston CI runs. 

I'd suggest adding something like this to the [Before you Publish wiki page](https://github.com/elementary/houston/wiki/Before-You-Publish). 

Some sources of information are:
- https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7#1227
- Chats on Gitter

Side note, when/if this is included I'd love to also write something for the [Getting Started](https://elementary.io/docs/code/getting-started#getting-started)

**Comment by cassidyjames** [comment]
I've included similar information in the wiki at https://github.com/elementary/houston/wiki/Before-You-Publish. Thanks for the suggestion!

**Comment by bbuhler** [comment]
@cassidyjames I think it could be helpful to mention what needs to be changed in the build files on that branch.

I'm a beginner and followed the website documentation by just using the elementary/debian-template. I have no clue about what dependencies and versions of it I need for Loki. I found out by trial and error with Housten CI.

Maybe one can create a branch for Loki in elementary/debian-template repo as well.

I would be helpful also adding a section about packing for Loki on website documentation.
