### ISSUE TITLE
validate appstream files with libappstream-glib too

### ISSUE THREAD

**Issue by decathorpe** [elementary/houston#645]
I'm not sure this is the right project to request this because I couldn't find the relevant validation code, but here goes.

Currently `houston-ci` uses `appstreamcli` to validate appstream files, AFAICT. However, the most-used "Software Centers" (`gnome-software` by default on ubuntu, fedora, etc.). The two implementations have slight differences in how they handle errors, and how strict they are. So, it would be nice if - in addition to using `appstreamcli` - the appdata files would also be validated with `libappstream-glib`.

The command line for validating an appdata file with `libappstream-glib` looks like this:

```sh
appstream-util validate-relax --nonet /path/to/appstream.xml.file
```

If there is internet access during builds (I hope there's not), you could even drop the `--nonet` flag. But the example above is exactly the mandatory appdata validation step for fedora packages, so I guess it's a good starting point.

**Comment by btkostner** [comment]
This is the correct repo! Relevant code here: https://github.com/elementary/houston/blob/v2/src/worker/task/appstream/validate.ts. Should be pretty easy to add.

**Comment by decathorpe** [comment]
Any progress on this?

I'd submit a PR for this, but I've never used JS / TypeScript before.

**Comment by btkostner** [comment]
No work has been made for this yet. Code is here if you want to work on it though: https://github.com/elementary/houston/blob/v2/src/worker/task/appstream/validate.ts#L53

**Comment by decathorpe** [comment]
Seems like I put off learning TypeScript for long enough that this issue became obsolete. 😅  gnome-software switched from libappstream-glib to libappstream with versions 40.beta and later, and libappstream-glib is now more or less obsolete :tada:
