### ISSUE TITLE
Disable trackpad while mouse is plugged in

### ISSUE THREAD

**Issue by FernandWTF** [elementary/houston#655]
Hey, I would like very much if you guys can do the functionality that I mention in the title, neither with dconf or setttings am able to disable my trackpad when my laptop has a mouse connected, the current solution that I have is use this code ``xinput disable 15`` on the startups scripts, fifteen which is the id that the system give to my trackpad. Amazing job btw <3.

**Comment by btkostner** [comment]
This is the wrong repository for that issue. Please file an issue in the switchboard plugin repository here: https://github.com/elementary/switchboard-plug-mouse-touchpad
