### ISSUE TITLE
Don't edit packaging

### ISSUE THREAD

**Issue by codygarver** [elementary/houston#659]
This is bad practice, it's creating non reproducible builds, and general badness.

This error shouldn't be possible:
`dpkg-source: error: source package has two conflicting values - maya-calendar and io.elementary.calendar`

Houston stuck the string `io.elementary.calendar` in there somewhere at some point.

**Comment by codygarver** [comment]
Maybe the bug is Houston should be getting the changelog package name for the bump from `Source: my-package`, the first line of `debian/control`

**Comment by codygarver** [comment]
I think if I override the `name-domain` it's gonna fail for another reason, the appdata is `io.elementary.calendar` not `maya-calendar`.

**Comment by btkostner** [comment]
@codygarver I'm looking at the `debian/control` file for some checks, but after a huge pain trying to parse it, I just settled on a regex. I could possibly use the regex to find that name, but could also fail when there are multiple packages.

Any reason not to change the package to `io.elementary.calendar` to match the desktop and appstream info?

**Comment by codygarver** [comment]
@btkostner `Source:` is a unique line in `debian/control` and it's ALWAYS the 1st line, it should be easy and reliable to read.

The reason not to rename all the packages affected by this right now is because it's not part of the beta period fixes and I don't want to create new problems because CI is telling me it's a good time. I plan on gradually transitioning the package names and it's gonna take a little time and testing to make sure it goes well. I'm still traumatized by renaming all the binaries before the beta started...

**Comment by danrabbit** [comment]
This doesn't seem relevant anymore since we're moving to flatpak
