### ISSUE TITLE
Houston CI doesn't seem to be able to build Vocal

### ISSUE THREAD

**Issue by nathandyer** [elementary/houston#673]
I'm not sure if it's something dumb that I'm doing on my side, or if it's a problem with Houston CI, but I can't seem to make it build Vocal correctly. I've tried using the .travis.xml file directly from the Houston CI post, and have also tried modifying it slightly to mirror the .travis.xml files of other projects that I know are building on Houston CI, but none of them build for me. They all seem to be stuck because of unmet build dependencies. I'm [attaching a log](https://github.com/elementary/houston/files/2527553/vocal_houston_ci_travis_10_29.txt) of the most recent build, and will [link to my .travis.xml](https://github.com/needle-and-thread/vocal/blob/master/.travis.yml) file. Please advise.

**Comment by btkostner** [comment]
This looks like a basic case of incorrect dependencies in your debian control file. I would try installing Juno (in a vm) and then try installing all of the listed dependencies for your Juno build. One of them probably does not exist, or is renamed, on Juno.
