### ISSUE TITLE
Ensure GSettings are installed to correct path

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#707]
It looks like we're not enforcing that GSettings are installed to the correct path; for example, Bookmark Manager was accidentally installing to an example path:

https://github.com/bartzaalberg/bookmark-manager/blob/1.5.0/data/com.github.bartzaalberg.bookmark-manager.gschema.xml#L2:10

We should have a test the ensures any GSettings are scoped beneath the correct RDNN.

**Comment by cassidyjames** [comment]
https://github.com/bartzaalberg/bookmark-manager/issues/45

**Comment by danrabbit** [comment]
This is no longer relevant since inside flatpak gsettings now uses a keyfile backend
