### ISSUE TITLE
Ephemeral AppData contains a price but no Stripe key, making it show up as free

### ISSUE THREAD

**Issue by cassidyjames** [elementary/houston#753]
~Not sure what's going on.~ I've confirmed on multiple machines on both stable and master. A local `appstreamcli dump` shows the custom tag with the price, but the AppCenter client shows it as free. Other apps show up as paid correctly. I've also confirmed that it's not in the `paid-apps` gsetting.

**Edit:** It looks like the AppData is not getting the Stripe key added by Houston.

**Comment by btkostner** [comment]
Does ephemeral have stripe enabled? and did you enable it before making that release?

**Comment by cassidyjames** [comment]
@btkostnerit it had been enabled since the very first release, but it looks like it got disabled somehow :scream: I never hit the button, so I'm not sure what's up with that...

**Comment by cassidyjames** [comment]
Related issue filed at https://github.com/elementary/houston/issues/754, but we should see if we can confirm it was a stray click or something versus something automatic.

**Comment by cassidyjames** [comment]
So it looks like what happened here was something with the database losing the state, and requiring me to re-enable monetization.
