### ISSUE TITLE
Incorrect "AppCenter Dashboard GitHub Integration" link

### ISSUE THREAD

**Issue by volfpeter** [elementary/houston#768]
Hi guys!

I've finished my first Vala/Gtk application (thanks for the great guide) and I would like to submit it to AppCenter. Unfortunately the "AppCenter Dashboard GitHub Integration" link in the [Submission Process](https://github.com/elementary/houston/wiki/Submission-Process) wiki page seems to be broken, so I don't know how to proceed.

Any help would be appreciated.

Thanks!

**Comment by btkostner** [comment]
Updated and fixed

**Comment by volfpeter** [comment]
Thanks a lot!

**Comment by volfpeter** [comment]
Can I have one more question? Where should I look for the "up arrow icon in a green bubble" to submit my application for review?

**Comment by btkostner** [comment]
@volfpeter It should be on the dashboard when you are looking at the list of apps

**Comment by volfpeter** [comment]
@btkostner Do you mean in Settings / Applications (https://github.com/settings/installations)? Should AppCenter show up under "Authorized GitHub Apps" or is it enough if it's under in "Installed GitHub Apps"?

**Comment by btkostner** [comment]
@volfpeter nope, under https://developer.elementary.io/dashboard

**Comment by volfpeter** [comment]
Awesome. I don't think I've seen this link in the docs or on the wiki, although I might have missed it. Maybe it should be added to the Submission Process wiki page. I've found the link on https://developer.elementary.io, but it wasn't really obvious that I should proceed through the "Welcome back" button with the octacat.

Anyway, thanks a lot for the support!
