### ISSUE TITLE
Application build error: Dependency "granite" not found

### ISSUE THREAD

**Issue by volfpeter** [elementary/houston#769]
Hi,

I've tried publishing my application to AppCenter, but the build fails with this error: `meson.build:11:0: ERROR:  Dependency "granite" not found, tried pkgconfig`.

I've checked a couple of AppCenter applications on Github to try to figure out what I'm doing wrong, but I couldn't find the problem, so now I'm wondering if this has something to do with `houston`. Here is the full [build log](https://github.com/volfpeter/timer/issues/2).

Thanks!

**Comment by jeremyvaartjes** [comment]
Try adding granite as a dependency to your `/debian/control` file since this is what is used for building your debian package.

**Comment by tintou** [comment]
Yes exactly what @jeremyvaartjes said, you need to specify the dependencies you're using here https://github.com/volfpeter/timer/blob/master/debian/control#L5

**Comment by volfpeter** [comment]
Thanks guys! I guess I'll have to add `libunity-dev` as well then.
