### ISSUE TITLE
AppCenter does not distribute the correct version of Planner.

### ISSUE THREAD

**Issue by alainm23** [elementary/houston#775]
## Describe the bug
Hi guys, I'm the developer of Planner. I've uploaded an update (v2.2.6). In AppCenter the version is displayed correctly. However, when installed it is not the correct version. What could be happening?

### Screenshots or screen recordings
![image](https://user-images.githubusercontent.com/33765137/75355056-ea19c300-587b-11ea-8f70-bbc7535ee48e.png)

## Platform Information
 - OS: elementary OS
 - OS Version: Hera

## Additional context
I also noticed that the detail of the last update is not available, Is it normal?

![image](https://user-images.githubusercontent.com/33765137/75355290-42e95b80-587c-11ea-94cb-6f7c3789cc2c.png)

**Comment by danrabbit** [comment]
It looks like your data directory got pushed into your debian directory: https://github.com/alainm23/planner/tree/deb-packaging/data

So the package is preferring whatever is in that packaging branch

**Comment by danrabbit** [comment]
Actually it looks like all of planner is in that packaging branch. So that's definitely the problem

**Comment by alainm23** [comment]
Silly me 😥️, I've uploaded a new update to AppCenter, I hope it's fixed now.
