### ISSUE TITLE
New version of an app got accepted, but not showing up in AppCenter

### ISSUE THREAD

**Issue by stsdc** [elementary/houston#783]
New version of Monitor got accepted ~6 days ago, but new version is not visible in AppCenter desktop app nor web version: https://appcenter.elementary.io/com.github.stsdc.monitor/

Expected to see new 0.7.1 version visible in AppCenter, instead 0.6.2 still there.

Monitor repo: https://github.com/stsdc/monitor

**Comment by cassidyjames** [comment]
Something was clogged up on the back end, but @btkostner took care of it. New release is available, see: https://appcenter.elementary.io/com.github.stsdc.monitor/

**Comment by stsdc** [comment]
Thanks!
