### ISSUE TITLE
Internal error while running

### ISSUE THREAD

**Issue by mirkobrombin** [elementary/houston#786]
I'm trying to upload three applications but I always get the same error (Internal error while running) without any description
https://github.com/linuxhubit/catfacts/issues/1

**Comment by slawtul** [comment]
Hi Mirko,
what was the issue?

**Comment by mirkobrombin** [comment]
> Hi Mirko,
> what was the issue? I am facing the same. I wanted to publish my app but got Internal Error without any details

I assume an "Internal Error" as a few minutes later it was back up and running.

**Comment by slawtul** [comment]
I published an app twice and each time got Internal Error. Anyways, thanks for an answer. StackExchange, Discord, Stackoverflow seem dead.

**Comment by mirkobrombin** [comment]
> I published an app twice and each time got Internal Error. Anyways, thanks for an answer. StackExchange, Discord, Stackoverflow seem dead.

For technical problems I got more easily answered in the GitHub Issues, for everything else Reddit.

**Comment by slawtul** [comment]
Thanks Mirko. I have just uninstalled AppCenter from my github account. Elementary OS is user friendly (and I can confirm this) - but not developer friendly for sure. I give up for now - maybe someday in a future I will back again.
