### ISSUE TITLE
App repo not visible on the dashboard.

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/houston#799]
I added the appcenter integration to my repo and made sure I set it up correctly.
![image](https://user-images.githubusercontent.com/25323231/92305358-c369e100-efb0-11ea-9d5d-5231ec97bf53.png)
But for some reason, it's not showing up on the dashboard.
![image](https://user-images.githubusercontent.com/25323231/92305367-d381c080-efb0-11ea-90b9-cb399b4fe81f.png)

**Comment by hezral** [comment]
I'm having the same issue. I have an existing app which is showing in AppCenter dashboard but a new app repo i added is not showing up. I've double check all files are nearly identical to the one already in AppCenter dashboard. 

Existing and showing: https://github.com/hezral/inspektor
New and not showing: https://github.com/hezral/quickword

**Comment by hezral** [comment]
I've tested by creating a new repo and copying everything without changing any files from https://github.com/hezral/inspektor and its the same, not showing up. 

https://github.com/hezral/inspektors is the clone

![image](https://user-images.githubusercontent.com/762735/99014299-69c3fb00-258d-11eb-92e4-609f35958b97.png)

Also https://developer.elementary.io/dashboard times out everytime i added a new repo in the configuration of AppCenter in Github.

**Comment by judirraquel** [comment]
I'm having the same issue. I waiting can upload my application soon.

**Comment by phase1geo** [comment]
I also seem to be running into this issue with my phase1geo/TextShine application.  I have the repository enabled in GitHub through the AppCenter Dashboard; however, after creating a 1.0.0 release, the repository is not showing up in the AppCenter developer dashboard.

**Comment by dar5hak** [comment]
I faced this with https://github.com/elfenware/obliviate, and decided to have a go at fixing it. But I couldn't get Houston to run locally.

@btkostner @cassidyjames Extremely sorry for the direct mention, but it seems there are six app releases blocked due to this issue. Can you help with this?

**Comment by RajSolai** [comment]
Same Issue with my application https://github.com/RajSolai/lroton Just trying for Months to get into the dashboard

**Comment by hezral** [comment]
I've just removed and readded my repo and now its showing. 
Thanks to whoever that fixed this :)

**Comment by dar5hak** [comment]
@hezral Removed and readded where? If it wasn't on the dashboard in the first place, how did you remove it?

**Comment by hezral** [comment]
I had 2 repo on the AppCenter configurations on Github. Removed those and readded it.

**Comment by dar5hak** [comment]
Ah okay, I had granted org-wide access. Working now with selected repos. Thanks a lot! 🚀

**Comment by hezral** [comment]
Cool 👍🏻

**Comment by hezral** [comment]
Still don't know who or what fixed this do we can close this off

**Comment by RajSolai** [comment]
Working perfect Right now , Nice !

**Comment by btkostner** [comment]
This was fixed when we moved from one of GitHub's older API endpoints to a newer one. I'm assuming they found the bug and fixed it in an update before. I'm going to close this now that it seems everyone can view their project. Let me know if this problem happens again.

**Comment by syfds** [comment]
I had the same issue with a specific repository today. Instruction in the last comment of @dar5hak helped to solve the problem.
