### ISSUE TITLE
create and use houston-colored label

### ISSUE THREAD

**Issue by aroman** [elementary/houston#91]
that's #3A416F.

when adding a repository, we should check if this label exists and and create it if not

**Comment by fabianthoma** [comment]
Should we also let the developers change that label once it exists? as in save the label ID and then just use it, whatever it says and whatever it looks like? Cause I think we should allow for devs to customize their issue workflow

**Comment by aroman** [comment]
i think should let them change the label color if they want. that's why I was suggesting that we create the label (and set the color) at the time that we add the repository.

We won't be able to allow them to change the text, though. GitHub labels do not have IDs — the only way to refer to them via the API is by their name, which is guaranteed to be unique.

**Comment by btkostner** [comment]
If we really wanted to, we could have an issue label name variable in the repo's .apphub file.
