### ISSUE TITLE
Position of buttons on firefox off

### ISSUE THREAD

**Issue by fabianthoma** [elementary/houston#94]
On firefox the Button Positions are off by quite a bit, not sure what exactly is causing it:
![bildschirmfoto von 2015-12-26 14 05 05](https://cloud.githubusercontent.com/assets/1058124/12006492/dbd1c6ce-abd9-11e5-804e-0263bb0e89ff.png)
left = chrome
right = firefox

**Comment by btkostner** [comment]
this should be fixed in 0.1.8 branch, but I don't have firefox to check

**Comment by btkostner** [comment]
fixed as of 0.1.8
