### ISSUE TITLE
Add a way to restrict access to the development instance

### ISSUE THREAD

**Issue by danrabbit** [elementary/houston#95]
It seems like not long from now we're going to want to have a couple of beta testers to work though some of the issues in actual use. We're going to need some kind of whitelist mechanism to restrict access for requesting builds on our instance of houston

**Comment by btkostner** [comment]
A simple github account permission scheme would work. We could add permission for beta usage, app approving, and an admin option for unrestricted access.

**Comment by danrabbit** [comment]
That sounds like a great idea :)

**Comment by btkostner** [comment]
Started working in the [permission branch](https://github.com/elementary/houston/tree/permission).
